--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ColinHDev/CPlot
build-by-default: true
branches:
- development
projects:
  CPlot:
    path: ""
    libs:
    - src: dktapps-pm-pl/pmforms/pmforms
      version: ^1.0.0
...
