--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ColinHDev/CPlot
projects:
  CPlot:
    path: ""
    lint:
      phpstan: false
    libs:
    - src: dktapps-pm-pl/pmforms/pmforms
      version: ^2.0.0
    - src: poggit/libasynql/libasynql
      version: ^4.0.1
    - src: sof3/await-generator/await-generator
      version: ^3.1.0
    - src: ColinHDev/libAsyncEvent/libAsyncEvent
      version: ^1.0.0
...
