name: CPlot
main: ColinHDev\CPlot\CPlot
version: "1.0.0"

api: 4.0.0

author: ColinHDev
website: https://github.com/ColinHDev

permissions:

    cplot.command.plot:
        default: true
    cplot.subcommand.add:
        default: true
    cplot.subcommand.auto:
        default: true
    cplot.subcommand.border:
        default: true
    cplot.subcommand.claim:
        default: true
    cplot.subcommand.clear:
        default: true
    cplot.subcommand.denied:
        default: true
    cplot.subcommand.deny:
        default: true
    cplot.subcommand.flag:
        default: true
    cplot.subcommand.generate:
        default: op
    cplot.subcommand.helpers:
        default: true
    cplot.subcommand.help:
        default: true
    cplot.subcommand.info:
        default: true
    cplot.subcommand.merge:
        default: true
    cplot.subcommand.remove:
        default: true
    cplot.subcommand.reset:
        default: true
    cplot.subcommand.schematic:
        default: op
    cplot.subcommand.setting:
        default: true
    cplot.subcommand.trusted:
        default: true
    cplot.subcommand.trust:
        default: true
    cplot.subcommand.undeny:
        default: true
    cplot.subcommand.untrust:
        default: true
    cplot.subcommand.visit:
        default: true
    cplot.subcommand.wall:
        default: true
    cplot.subcommand.warp:
        default: true

    cplot.admin.add:
        default: op
    cplot.admin.border:
        default: op
    cplot.admin.clear:
        default: op
    cplot.admin.deny:
        default: op
    cplot.admin.flag:
        default: op
    cplot.admin.merge:
        default: op
    cplot.admin.remove:
        default: op
    cplot.admin.reset:
        default: op
    cplot.admin.trust:
        default: op
    cplot.admin.undeny:
        default: op
    cplot.admin.untrust:
        default: op
    cplot.admin.wall:
        default: op
    cplot.admin.warp:
        default: op

    cplot.bypass.deny:
        default: op

    cplot.claimPlots.4:
        default: true
    cplot.claimPlots.unlimited:
        default: op

    cplot.flag.title:
        default: true
    cplot.flag.plot_enter:
        default: true
    cplot.flag.plot_leave:
        default: true
    cplot.flag.message:
        default: op
    cplot.flag.spawn:
        default: op
    cplot.flag.item_drop:
        default: true
    cplot.flag.item_pickup:
        default: true
    cplot.flag.pvp:
        default: true
    cplot.flag.pve:
        default: true
    cplot.flag.explosion:
        default: true
    cplot.flag.burning:
        default: true
    cplot.flag.flowing:
        default: true
    cplot.flag.growing:
        default: true
    cplot.flag.player_interact:
        default: true
    cplot.flag.server_plot:
        default: op
    cplot.flag.check_offlinetime:
        default: op
    cplot.flag.place:
        default: true
    cplot.flag.break:
        default: true
    cplot.flag.use:
        default: true

    cplot.interact.road:
        default: op
    cplot.interact.plot:
        default: op
    cplot.place.road:
        default: op
    cplot.place.plot:
        default: op
    cplot.break.road:
        default: op
    cplot.break.plot:
        default: op
    cplot.pvp.road:
        default: op
    cplot.pvp.plot:
        default: op