name: CPlot
main: ColinHDev\CPlot\CPlot
version: "1.0.0"

api: 4.0.0

author: ColinHDev
website: https://github.com/ColinHDev

permissions:

    cplot.command.plot:
        default: true
    cplot.subcommand.generate:
        default: op
    cplot.subcommand.merge:
        default: true
    cplot.subcommand.schematic:
        default: op

    cplot.admin.merge:
        default: op