# decide if only subcommands a player has permissions for should be shown in the help menu
# possible values: true, false
# default value: true
help.checkPermission: true

# decide if the plugin should use a player's offline data file to fetch the last time he played or should use the data from the plugin's database
# possible values: database, offline_data
# default value: database
lastPlayed.origin: "database"

# settings that are used for a plot world when generating
worldSettings:

    # schematic for the road of the plot world
    # default value: "default" (no schematic)
    roadSchematic: "default"
    # schematic for the merged road of the plot world
    # default value: "default" (no schematic)
    mergeRoadSchematic: "default"
    # schematic for the plots of the plot world
    # default value: "default" (no schematic)
    plotSchematic: "default"

    # the width of the street
    # default value: 7
    # minimum value: 3
    roadSize: 7
    # the size of the plot
    # default value: 32
    # minimum value: 5
    plotSize: 32
    # the hight of the plot
    # default value: 64
    # maximum value: 254
    # minimum value: 5
    groundSize: 64

    # the block that makes up the street
    # default value: "Oak Planks"
    roadBlock: "Oak Planks"
    # the block that makes up the border of the plot
    # default value: "Smooth Stone Slab"
    borderBlock: "Smooth Stone Slab"
    # the block that makes up the border of the plot when it is claimed
    # default value: "Cobblestone Slab"
    borderBlockOnClaim: "Cobblestone Slab"

    # the block that makes up the floor of the plot
    # default value: "Grass"
    plotFloorBlock: "Grass"
    # the block with which the plot is filled
    # default value: "Dirt"
    plotFillBlock: "Dirt"
    # the block that makes up the bottom of the plots
    # default value: "Bedrock"
    plotBottomBlock: "Bedrock"

# database settings
database:
    # define which provider will be used
    provider: "sqlite"
    # settings for the SQLite provider
    sqlite:
        # folder of the SQLite database file
        folder: "plugin_data/CPlot/"
        # file of the SQLite database
        file: "CPlot.sqlite"
    # TODO: more provider

# economy settings
economy:
    # define which economy provider will be used
    # possible values: "", ceconomy
    # default value: ""
    # TODO: more economy provider
    provider: ""

    # define how much it costs to claim a plot
    claimPrice: 0.0
    # define how much it costs to clear a plot
    clearPrice: 0.0
    # define how much it costs to merge plots
    mergePrice: 0.0
    # define how much it costs to reset a plot
    resetPrice: 0.0