# If upon executing the "/plot auto" command, the player is not in a plot world, decide whether a backup plot world
# should be used to find a free plot.
# Possible values: A valid plot world name or false.
auto.fallbackWorld: false

# Decide if upon executing the "/plot auto" command, the found free plot should be automatically claimed for the player.
# Possible values: true, false
# Default value: true
auto.automaticClaim: true

# decide if only subcommands a player has permissions for should be shown in the help menu
# possible values: true, false
# default value: true
help.checkPermission: true

# decide if the plugin should use a player's offline data file to fetch the last time he played or should use the data from the plugin's database
# possible values: database, offline_data
# default value: database
lastPlayed.origin: "database"

# settings that are used for a plot world when generating
worldSettings:
    # Define the default biome of the world which is applied to every part of the roads and plots.
    # Default value: "plains"
    biome: "plains"

    # schematic for the road of the plot world
    # default value: "default" (no schematic)
    roadSchematic: "default"
    # schematic for the merged road of the plot world
    # default value: "default" (no schematic)
    mergeRoadSchematic: "default"
    # schematic for the plots of the plot world
    # default value: "default" (no schematic)
    plotSchematic: "default"

    # the width of the street
    # default value: 7
    # minimum value: 3
    roadSize: 7
    # the size of the plot
    # default value: 32
    # minimum value: 5
    plotSize: 32
    # the hight of the plot
    # default value: 64
    # maximum value: 254
    # minimum value: 5
    groundSize: 64

    # the block that makes up the street
    # default value: "Oak Planks"
    roadBlock: "Oak Planks"
    # the block that makes up the border of the plot
    # default value: "Smooth Stone Slab"
    borderBlock: "Smooth Stone Slab"

    # the block that makes up the floor of the plot
    # default value: "Grass"
    plotFloorBlock: "Grass"
    # the block with which the plot is filled
    # default value: "Dirt"
    plotFillBlock: "Dirt"
    # the block that makes up the bottom of the plots
    # default value: "Bedrock"
    plotBottomBlock: "Bedrock"

# Define the default values of all flags.
flag:
    # Define the default value of the plot_enter flag.
    # default: "false"
    plot_enter: "false"
    # Define the default value of the plot_leave flag.
    # default: "false"
    plot_leave: "false"
    # Define the default value of the message flag.
    # default: ""
    message: ""

    # Define the default value of the item_drop flag.
    # default: "true"
    item_drop: "true"
    # Define the default value of the item_pickup flag.
    # default: "true"
    item_pickup: "true"

    # Define the default value of the pvp flag.
    # default: "false"
    pvp: "false"
    # Define the default value of the pve flag.
    # default: "false"
    pve: "false"
    # Define the default value of the explosion flag.
    # default: "false"
    explosion: "false"
    # Define the default value of the burning flag.
    # default: "false"
    burning: "false"
    # Define the default value of the flowing flag.
    # default: "true"
    flowing: "true"
    # Define the default value of the growing flag.
    # default: "true"
    growing: "true"
    # Define the default value of the player_interact flag.
    # default: "false"
    player_interact: "false"
    # Define the default value of the server_plot flag.
    # default: "false"
    server_plot: "false"

    # Define the default value of the place flag.
    # default: "[]"
    place: "[]"
    # Define the default value of the break flag.
    # default: "[]"
    break: "[]"
    # Define the default value of the use flag.
    # default: "[]"
    use: "[]"

# Define the default values of all settings.
setting:
    # Define the default value of the inform_trusted_add setting.
    # default: "true"
    inform_trusted_add: "true"
    # Define the default value of the inform_trusted_remove setting.
    # default: "true"
    inform_trusted_remove: "true"

    # Define the default value of the inform_helper_add setting.
    # default: "true"
    inform_helper_add: "true"
    # Define the default value of the inform_helper_remove setting.
    # default: "true"
    inform_helper_remove: "true"

    # Define the default value of the inform_denied_add setting.
    # default: "true"
    inform_denied_add: "true"
    # Define the default value of the inform_denied_remove setting.
    # default: "true"
    inform_denied_remove: "true"

    # Define the default value of the inform_plot_inactive setting.
    # default: "false"
    inform_plot_inactive: "false"

    # Define the default value of the inform_plot_rate_add setting.
    # default: "true"
    inform_plot_rate_add: "true"

    # Define the default value of the warn_flag_item_drop setting.
    # default: "[false]"
    warn_flag_item_drop: "[false]"
    # Define the default value of the warn_change_flag_item_drop setting.
    # default: "[false]"
    warn_change_flag_item_drop: "[false]"
    # Define the default value of the teleport_change_flag_item_drop setting.
    # default: "[]"
    teleport_change_flag_item_drop: "[]"

    # Define the default value of the warn_flag_item_pickup setting.
    # default: "[false]"
    warn_flag_item_pickup: "[false]"
    # Define the default value of the warn_change_flag_item_pickup setting.
    # default: "[false]"
    warn_change_flag_item_pickup: "[false]"
    # Define the default value of the teleport_change_flag_item_pickup setting.
    # default: "[]"
    teleport_change_flag_item_pickup: "[]"

    # Define the default value of the warn_flag_pvp setting.
    # default: "[true]"
    warn_flag_pvp: "[true]"
    # Define the default value of the warn_change_flag_pvp setting.
    # default: "[true]"
    warn_change_flag_pvp: "[true]"
    # Define the default value of the teleport_change_flag_pvp setting.
    # default: "[true]"
    teleport_change_flag_pvp: "[true]"

    # Define the default value of the warn_flag_pve setting.
    # default: "[true]"
    warn_flag_pve: "[true]"
    # Define the default value of the warn_change_flag_pve setting.
    # default: "[true]"
    warn_change_flag_pve: "[true]"
    # Define the default value of the teleport_change_flag_pve setting.
    # default: "[true]"
    teleport_change_flag_pve: "[true]"

    # Define the default value of the warn_flag_explosion setting.
    # default: "[true]"
    warn_flag_explosion: "[true]"
    # Define the default value of the warn_change_flag_explosion setting.
    # default: "[true]"
    warn_change_flag_explosion: "[true]"
    # Define the default value of the teleport_change_flag_explosion setting.
    # default: "[]"
    teleport_change_flag_explosion: "[]"

# database settings
database:
    # The database type. "sqlite" and "mysql" are supported.
    type: sqlite

    # Edit these settings only if you choose "sqlite".
    sqlite:
        # The file name of the database in the plugin data folder.
        # You can also put an absolute path here.
        file: CPlot.sqlite
    # Edit these settings only if you choose "mysql".
    mysql:
        host: 127.0.0.1
        # Avoid using the "root" user for security reasons.
        username: root
        password: ""
        schema: CPlot
    # The maximum number of simultaneous SQL queries
    # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
    worker-limit: 1

# Change the settings for CPlot's economy plugin integration.
economy:
    # Define the economy plugin, that will be used.
    # Supported plugins: BedrockEconomy, Capital
    provider: ""
    # Edit these settings only if you choose "Capital".
    capital:
        selector: []
        # Since Capital does not support the configuration of currency symbols, you can use this setting to define the
        # symbol of your currency that will be used in messages by this plugin or add your currency unit to all messages
        # in the language files, as it would be intended by SOFe, the creator of Capital.
        # Default value: "$"
        currency: "$"

    # Define the price it costs to claim a plot.
    claimPrice: 0.0
    # Define the charge reason which is maybe saved in the economy plugin's database when a plot is claimed.
    claimReason: "plot claiming"
    # Define the price it costs to clear a plot.
    clearPrice: 0.0
    # Define the charge reason which is maybe saved in the economy plugin's database when a plot is cleared.
    clearReason: "plot clearing"
    # Define the price it costs to merge plots.
    mergePrice: 0.0
    # Define the charge reason which is maybe saved in the economy plugin's database when plots are merged.
    mergeReason: "plot merging"
    # Define the price it costs to reset a plot.
    resetPrice: 0.0
    # Define the charge reason which is maybe saved in the economy plugin's database when a plot is resetted.
    resetReason: "plot resetting"

# Change the settings for CPlot's language integration.
language:
    # Set the default language that will be used when translating a message for a player, whose language is not supported.
    fallback: "en_us" # American English

    # Set aliases for specific languages that may be used by players. (This can be useful if a certain language is
    # nearly the same as another one. This way you can just set one language as the alias of the other one, so you will
    # not have to copy and maintain two files with the same content. E.g.: "en_us": "en_gb")
    aliases:
        de_at: "de_de" # Austrian German
        de_ch: "de_de" # Swiss German
        en_gb: "en_us" # British English