inform_add_trusted:
    default: true
    type: "boolean (Wahrheitswert)"
    description: "Erhalte eine Benachrichtigung, wenn du auf einem Grundstück als Vertrauter hinzugefügt wirst."
    category: "players"
inform_remove_trusted:
    default: true
    type: "boolean (Wahrheitswert)"
    description: "Erhalte eine Benachrichtigung, wenn du auf einem Grundstück als Vertrauter entfernt wirst."
    category: "players"

inform_add_helper:
    default: true
    type: "boolean (Wahrheitswert)"
    description: "Erhalte eine Benachrichtigung, wenn du auf einem Grundstück als Helfer hinzugefügt wirst."
    category: "players"
inform_remove_helper:
    default: true
    type: "boolean (Wahrheitswert)"
    description: "Erhalte eine Benachrichtigung, wenn du auf einem Grundstück als Helfer entfernt wirst."
    category: "players"

inform_add_denied:
    default: true
    type: "boolean (Wahrheitswert)"
    description: "Erhalte eine Benachrichtigung, wenn du auf einem Grundstück als Gesperrter hinzugefügt wirst."
    category: "players"
inform_remove_denied:
    default: true
    type: "boolean (Wahrheitswert)"
    description: "Erhalte eine Benachrichtigung, wenn du auf einem Grundstück als Gesperrter entfernt wirst."
    category: "players"

inform_plot_inactive:
    default: false
    type: "boolean (Wahrheitswert)"
    description: "Erhalte eine Benachrichtigung, wenn das Grundstück, dass du betrittst, ineinem der angegebenen Werte entspricht."
    category: "plots"

inform_add_plot_rate:
    default: true
    type: "boolean (Wahrheitswert)"
    description: "Erhalte eine Benachrichtigung, wenn eine Bewertung zu deinem Grundstück hinzugefügt wird."
    category: "plots"

warn_flag_title:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag title einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_title:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag title auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_title:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag title auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_plot_enter:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag plot_enter einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_plot_enter:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag plot_enter auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_plot_enter:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag plot_enter auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_plot_leave:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag plot_leave einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_plot_leave:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag plot_leave auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_plot_leave:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag plot_leave auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_message:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag message einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_message:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag message auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_message:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag message auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_spawn:
    default: [true]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag spawn einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_spawn:
    default: [true]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag spawn auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_spawn:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag spawn auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_item_drop:
    default: [false]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag item_drop einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_item_drop:
    default: [false]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag item_drop auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_item_drop:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag item_drop auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_item_pickup:
    default: [false]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag item_pickup einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_item_pickup:
    default: [false]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag item_pickup auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_item_pickup:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag item_pickup auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_pvp:
    default: [true]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag pvp einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_pvp:
    default: [true]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag pvp auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_pvp:
    default: [true]
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag pvp auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_pve:
    default: [true]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag pve einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_pve:
    default: [true]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag pve auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_pve:
    default: [true]
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag pve auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_explosion:
    default: [true]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag explosion einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_explosion:
    default: [true]
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag explosion auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_explosion:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag explosion auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_burning:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag burning einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_burning:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag burning auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_burning:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag burning auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_flowing:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag flowing einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_flowing:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag flowing auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_flowing:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag flowing auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_growing:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag growing einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_growing:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag growing auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_growing:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag growing auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_player_interact:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag player_interact einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_player_interact:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag player_interact auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_player_interact:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag player_interact auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_server_plot:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag server_plot einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_server_plot:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag server_plot auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_server_plot:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag server_plot auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_check_inactive:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag check_inactive einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_check_inactive:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag check_inactive auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_check_inactive:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag check_inactive auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_place:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag place einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_place:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag place auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_place:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag place auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_break:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag break einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_break:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag break auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_break:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag break auf einen der angegebenen Werte gesetzt wird."
    category: "flags"

warn_flag_use:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, dass du betrittst, der Wert der Flag use einem der angegebenen Werte entspricht."
    category: "flags"
warn_change_flag_use:
    default: []
    type: "array (Feld)"
    description: "Erhalte eine Warnung, wenn auf dem Grundstück, auf dem du dich befindest, der Wert der Flag use auf einen der angegebenen Werte gesetzt wird."
    category: "flags"
teleport_change_flag_use:
    default: []
    type: "array (Feld)"
    description: "Du wirst außerhalb des Grundstücks teleportiert, wenn auf diesem der Wert der Flag use auf einen der angegebenen Werte gesetzt wird."
    category: "flags"